# Generated by Django 3.1.8 on 2021-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='bonus_pickup',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekday_pickup',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
