# Generated by Django 3.1.8 on 2021-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210506_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='weekday_pickup',
            new_name='weekly_pickup',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_completed',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
