# Generated by Django 3.1.8 on 2021-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210507_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
