# Generated by Django 3.1.8 on 2021-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210507_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
