# Generated by Django 3.1.8 on 2021-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210507_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
